parameters:
    bin.provider: '%kernel.project_dir%/index.js'
    url_filters:
      - '.*\.(pdf|jpg|jpeg|gif|png)'
    env(CHROMIUM_PARALLEL_PROCESSES): 3
    env(AUDIT_PAGE_SIZE_THRESHOLD): 5242880
    env(AUDIT_RESOURCE_LOAD_THRESHOLD): 1000
    env(AUDIT_RESOURCE_SIZE_THRESHOLD): 1048576
    audit.page_size_threshold: '%env(AUDIT_PAGE_SIZE_THRESHOLD)%'
    audit.resource_load_threshold: '%env(AUDIT_RESOURCE_LOAD_THRESHOLD)%'
    audit.resource_size_threshold: '%env(AUDIT_RESOURCE_SIZE_THRESHOLD)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    Webduck\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Bus,Console,Domain}'

    Webduck\Bus\Handler\:
        resource: '../src/Bus/Handler'
        public: true

    Webduck\Bus\Processor\:
        resource: '../src/Bus/Processor'
        tags:
            - { name: 'enqueue.client.processor' }

    Webduck\Http\Controller\:
        resource: '../src/Http/Controller/*'
        tags: ['controller.service_arguments']

    Webduck\Console\Command\:
        resource: '../src/Console/Command'
        tags: ['console.command']

    Webduck\Console\Helper\:
        resource: '../src/Console/Helper'
        public: true

    Webduck\Domain\Transformer\:
        resource: '../src/Domain/Transformer'
        public: true

    Webduck\Domain\Audit\:
        resource: '../src/Domain/Audit'
        public: true
        exclude: '../src/{AuditCollection.php,AuditInterface.php}'

    Webduck\Domain\Audit\AuditCollection:
        class: Webduck\Domain\Audit\AuditCollection
        public: true
        calls:
            - [ 'add', [ '@Webduck\Domain\Audit\ConsoleErrorsAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\ExceptionAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\PageSizeAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\ResourceLoadAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\ResourceSizeAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\SecurityAudit' ] ]
            - [ 'add', [ '@Webduck\Domain\Audit\ViolationAudit' ] ]

    Webduck\Domain\Audit\PageSizeAudit:
        class: Webduck\Domain\Audit\PageSizeAudit
        arguments: [ '%audit.page_size_threshold%' ]
        public: true

    Webduck\Domain\Audit\ResourceLoadAudit:
        class: Webduck\Domain\Audit\ResourceLoadAudit
        arguments: [ '%audit.resource_load_threshold%' ]
        public: true

    Webduck\Domain\Audit\ResourceSizeAudit:
        class: Webduck\Domain\Audit\ResourceSizeAudit
        arguments: [ '%audit.resource_size_threshold%' ]
        public: true

    Webduck\Domain\Provider\BrowseCollectionProvider:
        class: Webduck\Domain\Provider\BrowseCollectionProvider
        arguments: [ '%bin.provider%', '%env(CHROMIUM_PARALLEL_PROCESSES)%' ]

    Webduck\Bus\Handler\AuditSiteHandler:
        public: true
        calls: [ [ 'setDefaultUriFilters', [ '%url_filters%' ] ] ]

    Webduck\Bus\Handler\AuditSitemapHandler:
        public: true
        calls: [ [ 'setDefaultUriFilters', [ '%url_filters%' ] ] ]

    Webduck\Domain\Storage\ReportStorage:
        class: Webduck\Domain\Storage\ReportStorage
        public: true
        arguments:
          - '%kernel.project_dir%/var/reports'
          - '@Webduck\Domain\Transformer\ReportToJsonTransformer'
          - '@Webduck\Domain\Transformer\JsonToReportTransformer'
